name: Build with Gradle

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    name: Builds and tests for Gradle under Earthly
    runs-on: ubuntu-latest

    steps:
      - name: Use Earthly
        uses: earthly/actions-setup@v1
        with:
          version: "latest"

      - name: Clone repository
        uses: actions/checkout@master

      - name: Restore Gradle caches
        uses: actions/cache@master
        env:
          cache-name: gradle-cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{hashFiles('**/build.gradle') }}
          # TODO: See discussion: https://github.com/jeremylong/DependencyCheck/issues/2560#issuecomment-702098748
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build and test with Gradle under Earthly
        run: earthly +build-with-gradle
