name: Build with Maven

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build:
    name: Builds and tests for Maven under Batect
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Restore Batect caches
        uses: actions/cache@master
        env:
          cache-name: batect-cache
        with:
          path: ~/.batect
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/batect.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Manage Batect telemetry
        run: ./batect --permanently-enable-telemetry

      - name: Restore Maven caches
        uses: actions/cache@master
        env:
          cache-name: maven-cache
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build and test with Maven under Batect
        run: ./batect build-with-maven

      - name: Execute run script asuming build with Maven
        run: ./batect -o quiet run-with-maven

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: target/modern-java-practices*.jar

      - name: Save site
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: target/site/
